### ISSUE TITLE
Path n'est pas un chemin absolue (chokidar)

### ISSUE THREAD

**Issue by Hydrog3n** [Hydrog3n/upload-screenshot#2]

**Comment by Hydrog3n** [comment]
Problème viendrait de l'event, moved sur os x et changed sur Arch linux

**Comment by soyuka** [comment]
Tu peux donner un exemple ? relatif au cwd ? En tout cas suffit de rajouter [`path.resolve()`](https://nodejs.org/api/path.html#path_path_resolve_from_to)

**Comment by Hydrog3n** [comment]
Alors peut-être qu'avec la PR que tu as fait ça a changé ça il faut voir avec @hardware

**Comment by Hydrog3n** [comment]
SI non le `console.log(details)` de hard http://pix.hydrog3n.fr/hG le mien http://pix.hydrog3n.fr/hL
